import pandas as pd

SPLIT_DATA = {
    "ERD_Battery_MR": pd.DataFrame([
        {
            "Start Time": "",
            "Stop Time": "",
            "Measured Time": "0:00:00",
            "SP": "",
            "Speed": "0.00",
            "Fitters": "",
            "Helpers": "",
            "Total Time": "0:00:00",
            "MTE1 Time": "",
            "Component/phase": "",
            "Remarks": "This row is not in use"
        },
        {
            "Start Time": "9:00:00",
            "Stop Time": "9:25:00",
            "Measured Time": "0:25:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:25:00",
            "MTE1 Time": "0:25:00",
            "Component/phase": "Preparation",
            "Remarks": "Site and Tools preparation"
        },
        {
            "Start Time": "9:25:00",
            "Stop Time": "9:27:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Preparation",
            "Remarks": "ERD shutdown"
        },
        {
            "Start Time": "9:27:00",
            "Stop Time": "9:32:00",
            "Measured Time": "0:05:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:05:00",
            "MTE1 Time": "0:05:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Take-5 process"
        },
        {
            "Start Time": "9:32:00",
            "Stop Time": "9:34:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Remove the power cables from controller terminal block"
        },
        {
            "Start Time": "9:34:00",
            "Stop Time": "9:36:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Open the drive cover"
        },
        {
            "Start Time": "9:36:00",
            "Stop Time": "9:40:00",
            "Measured Time": "0:04:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:04:00",
            "MTE1 Time": "0:04:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Disconnect the power cables in drive"
        },
        {
            "Start Time": "9:40:00",
            "Stop Time": "9:48:00",
            "Measured Time": "0:08:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:08:00",
            "MTE1 Time": "0:08:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Remove the wires from auxiliary contacts"
        },
        {
            "Start Time": "9:48:00",
            "Stop Time": "9:50:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Remove the main contactor coil supply"
        },
        {
            "Start Time": "9:50:00",
            "Stop Time": "9:55:00",
            "Measured Time": "0:05:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:05:00",
            "MTE1 Time": "0:05:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Cut the cable ties and remove the cables from drive"
        },
        {
            "Start Time": "9:55:00",
            "Stop Time": "9:56:00",
            "Measured Time": "0:01:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:01:00",
            "MTE1 Time": "0:01:00",
            "Component/phase": "Removing main contactor",
            "Remarks": "Remove the contactor from DIN rail"
        },
        {
            "Start Time": "9:56:00",
            "Stop Time": "9:58:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Installing contactor in DIN rail"
        },
        {
            "Start Time": "9:58:00",
            "Stop Time": "10:00:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Connect the power cables in terminal blocks"
        },
        {
            "Start Time": "10:00:00",
            "Stop Time": "10:02:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Connect the main contactor coil supply"
        },
        {
            "Start Time": "10:02:00",
            "Stop Time": "10:10:00",
            "Measured Time": "0:08:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:08:00",
            "MTE1 Time": "0:08:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Connect the wires in auxiliary contacts"
        },
        {
            "Start Time": "10:10:00",
            "Stop Time": "10:15:00",
            "Measured Time": "0:05:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:05:00",
            "MTE1 Time": "0:05:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Route the power cable to drive using cable tie"
        },
        {
            "Start Time": "10:15:00",
            "Stop Time": "10:19:00",
            "Measured Time": "0:04:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:04:00",
            "MTE1 Time": "0:04:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Connect the power cables in drive"
        },
        {
            "Start Time": "10:19:00",
            "Stop Time": "10:21:00",
            "Measured Time": "0:02:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:02:00",
            "MTE1 Time": "0:02:00",
            "Component/phase": "Installing main contactor",
            "Remarks": "Close the drive cover"
        },
        {
            "Start Time": "10:21:00",
            "Stop Time": "10:26:00",
            "Measured Time": "0:05:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:05:00",
            "MTE1 Time": "0:05:00",
            "Component/phase": "Finalize work",
            "Remarks": "Switch on the mains, test run"
        },
        {
            "Start Time": "10:26:00",
            "Stop Time": "10:31:00",
            "Measured Time": "0:05:00",
            "SP": "",
            "Speed": "1.00",
            "Fitters": 1,
            "Helpers": "",
            "Total Time": "0:05:00",
            "MTE1 Time": "0:05:00",
            "Component/phase": "Finalize work",
            "Remarks": "Tools, materials, out of service board removing"
        },
    ])
}
